Repository toy-p/Pocket-Map, pull requests merged in 2023-07, with the labels that each got.

#16 Feat/album
  lib/config/route.dart
  lib/datas/models/Album.dart
  lib/screens/add_location_screen.dart
  lib/screens/select_Image.dart
  lib/utils/grid_photo.dart
  lib/view_model/imageProvider.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: 🎯 feature

#19 fix: 안드로이드 에뮬 실행 오류 fix
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Podfile.lock
  ios/Runner/Info.plist
Labels: 🛠 bugfix

#21 fix:안드로이드 빌드 오류
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  linux/CMakeLists.txt
  linux/my_application.cc
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  web/index.html
  web/manifest.json
  windows/CMakeLists.txt
  windows/runner/Runner.rc
  windows/runner/main.cpp
Labels: 🛠 bugfix

#22 bugfix : 디버깅 오류 수정 / feat: 파일 이미지 업로드 다시 구현
  android/app/src/main/AndroidManifest.xml
  lib/config/route.dart
  lib/screens/add_location_screen.dart
  pubspec.lock
  test/widget_test.dart
Labels: 🎯 feature, 🛠 bugfix

#23 feat : 마커 기능 추가
  .gitignore
  lib/screens/home_screen.dart
  lib/utils/address_search.dart
  lib/utils/kakao.dart
Labels: 🎯 feature
